app/home/forms.py
#!/usr/bin/env python 
# encoding: utf-8 
# 开发人员：li
# 开发团队：xiaoli
# 开发时间：2020/3/31 10:50
# 文件名称：forms.PY

from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField, PasswordField, FileField, TextAreaField, \
    SelectField, SelectMultipleField
from wtforms.validators import DataRequired, ValidationError, EqualTo,Email,Regexp
from app.models import Admin, User


class RegistForm(FlaskForm):
    name = StringField(
        label = "昵称",
        # 验证器
        validators = [
            DataRequired('请输入昵称！')
        ],
        description = "昵称",
        # 附加选项
        render_kw = {
            "class": "form-control input-lg",
            "placeholder": "请输入昵称！",
        }
    )
    email = StringField(
        label = "邮箱",
        # 验证器
        validators = [
            DataRequired('请输入邮箱！'),
            Email('邮箱格式不正确！')
        ],
        description = "邮箱",
        # 附加选项
        render_kw = {
            "class": "form-control input-lg",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label = "电话",
        # 验证器
        validators = [
            DataRequired('请输入电话！'),
            Regexp('1[3458]\\d{9}',message = '请输入正确的手机号码！')
        ],
        description = "电话",
        # 附加选项
        render_kw = {
            "class": "form-control input-lg",
            "placeholder": "请输入电话！",
        }
    )
    pwd = PasswordField(
        label = "密码",
        # 验证器
        validators = [
            DataRequired('请输入密码！')
        ],
        description = "密码",
        render_kw = {
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
            # 必须的选项
            # "required": "required"
        }
    )
    re_pwd = PasswordField(
        label = "确认密码",
        # 验证器
        validators = [
            DataRequired('请确认密码！'),
            EqualTo('pwd', message = "两次密码不一致")
        ],
        description = "确认密码",
        render_kw = {
            "class": "form-control input-lg",
            "placeholder": "请确认密码！",
        }
    )
    submit = SubmitField(
        "注册",
        render_kw = {
            # "id":"btn-sub",
            "class": "btn btn-lg btn-success btn-block",
            # "required": "required"
        }
    )

    #验证模型字段唯一性

    def validata_name(self,field):
        name = field.data
        user = User.query.filter_by(name =name).count()
        if user ==1:
            raise  ValidationError('昵称已经存在!')


    def validata_email(self,field):
        email = field.data
        user = User.query.filter_by(email =email).count()
        if user ==1:
            raise  ValidationError('邮箱已经存在!')

    def validata_phone(self,field):
        phone = field.data
        user = User.query.filter_by(phone =phone).count()
        if user ==1:
            raise  ValidationError('手机号码已经存在!')


class LoginForm(FlaskForm):
    name = StringField(
        label = "账号",
        # 验证器
        validators = [
            DataRequired('请输入账号！')
        ],
        description = "账号",
        # 附加选项
        render_kw = {
            "class": "form-control input-lg",
            "placeholder": "请输入账号！",
        }
    )
    pwd = PasswordField(
        label = "密码",
        # 验证器
        validators = [
            DataRequired('请输入密码！')
        ],
        description = "密码",
        render_kw = {
            "class": "form-control input-lg",
            "placeholder": "请输入密码！",
            # 必须的选项
            # "required": "required"
        }
    )
    submit = SubmitField(
        "登录",
        render_kw = {
            # "id":"btn-sub",
            "class": "btn btn-lg btn-primary btn-block",
            # "required": "required"
        }
    )


#会员修改资料表单
class UserDetailForm(FlaskForm):
    name = StringField(
        label = '昵称',
        # 验证器
        validators = [
            DataRequired('请输入昵称！')
        ],
        description = "昵称",
        # 附加选项
        render_kw = {
            "class": "form-control",
            "placeholder": "请输入昵称！",
        }
    )
    email = StringField(
        label = '邮箱',
        # 验证器
        validators = [
            DataRequired('请输入邮箱！'),
            Email('邮箱格式不正确！')
        ],
        description = "邮箱",
        # 附加选项
        render_kw = {
            "class": "form-control",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label = '手机号码',
        # 验证器
        validators = [
            DataRequired('请输入手机号码！'),
            Regexp('1[3458]\\d{9}', message = '请输入正确的手机号码！')
        ],
        description = "手机号码",
        # 附加选项
        render_kw = {
            "class": "form-control",
            "placeholder": "请输入电话！",
        }
    )
    face = FileField(
        label = '头像',
        validators = [
            DataRequired('请上传头像')
        ],
        description = '头像',
    )
    info  = TextAreaField(
        label = '简介',
        validators = [
            DataRequired('请输入简介'),
        ],
        description = '简介',
        render_kw = {
            "class": "form-control",
        }
    )
    submit = SubmitField(
        '保存修改',
        render_kw = {
            # "id":"btn-sub",
            "class": "btn btn-success",
            # "required": "required"
        }
    )


#密码
class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label = '旧密码',
        validators = [
            DataRequired('请输入旧密码！')
        ],
        description = "旧密码",
        render_kw = {
            "class": "form-control",
            "placeholder": "请输入旧密码！"
        }
    )
    new_pwd = PasswordField(
        label = '新密码',
        validators = [
            DataRequired('请输入新密码！')
        ],
        description = "新密码",
        render_kw = {
            "class": "form-control",
            "placeholder": "请输入新密码！"
        }
    )
    submit = SubmitField(
        '修改密码',
        render_kw = {
            "class": "btn btn-success"
        }
    )

    def validate_old_pwd(self,field):
        from flask import session
        pwd = field.data
        name = session.get('user')
        user = User.query.filter_by(
            name = name
        ).first()
        if not user.check_pwd(pwd):
            raise ValidationError('旧密码错误！')



class CommentForm(FlaskForm):
    content = TextAreaField(
        label = '内容',
        validators = [
            DataRequired('请输入内容')
        ],
        description = '内容',
        render_kw = {
            "id": "input_content"
        }

    )
    submit = SubmitField(
        '提交评论',
        render_kw = {
            "class": "btn btn-success",
            "id":"btn-sub"
        }
    )

app/home/__init__.py
#!/usr/bin/env python 
# coding: utf-8
# 开发人员：li
# 开发团队：xiaoli
# 开发时间：2020/3/31 10:49
# 文件名称：__init__.py.PY
#定义前端蓝图
from flask import  Blueprint

home = Blueprint('home',__name__)

import app.home.views

app/home/views.py
#!/usr/bin/env python 
# encoding: utf-8 
# 开发人员：li
# 开发团队：xiaoli
# 开发时间：2020/3/31 10:50
# 文件名称：views.PY
import datetime
import os
from functools import wraps
from werkzeug.utils import secure_filename
from app import db, app
from app.home.forms import RegistForm, LoginForm, UserDetailForm, PwdForm,CommentForm
from app.models import User, UserLog, Preview, Tag, Movie, Moviecol, Comment
from . import home
from flask import render_template, redirect, url_for, flash,request,session
from werkzeug.security import generate_password_hash
import uuid





# 访问限制处理器
def home_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        # 如果session中没有admin
        if 'user' not in session:
            return redirect(url_for('home.login', next = request.url))
        return f(*args, **kwargs)
    return decorated_function

# 改变文件名称
def change_filename(filename):
    fileinfo = os.path.splitext(filename)  # 分割成后缀名加前面标题
    filename = datetime.date.today().strftime("%Y-%m-%d") + str(uuid.uuid4().hex) + fileinfo[-1]
    return filename


# 电影界面进行标签筛选
#从上面可以看出：
#当get请求时，需要使用request.args来获取数据
#当post请求时，需要使用request.form来获取数据
@home.route('/<int:page>/',methods = ['GET'])
@home_login_req
def index(page = None):
    tags= Tag.query.all()
    page_data = Movie.query
    #标签
    tid = request.args.get('tid', 0)
    if int(tid) !=0:
        page_data = page_data.filter_by(tag_id =int(tid))
    star = request.args.get('star',0)
    #星级
    if int(star) !=0:
        page_data = page_data.filter_by(star = int(star))
    time = request.args.get('time',0)
    #上映时间
    if int(time) != 0:
        if int(time) ==1:
            page_data = page_data.order_by(Movie.addtime.desc())
        else:
            page_data = page_data.order_by(Movie.addtime.asc())
    #播放量
    playnum = request.args.get('playnum',0)
    if int(playnum) != 0:
        if int(playnum) ==1:
            page_data = page_data.order_by(Movie.playnum.desc())
        else:
            page_data = page_data.order_by(Movie.playnum.asc())
    #评论数量
    cm = request.args.get('cm',0)
    if int(cm) != 0:
        if int(cm) == 1:
            page_data = page_data.order_by(Movie.commentnum.desc())
        else:
            page_data = page_data.order_by(Movie.commentnum.asc())
    if page == None:
        page =1
    page_data = page_data.paginate(page = page,per_page = 10)
    p = dict(
        tid = tid,
        time = time,
        star = star,
        playnum = playnum,
        cm = cm,
    )
    return render_template('home/index.html',tags = tags,p = p,page_data=page_data)


# 登录
@home.route('/login/',methods = ['GET','POST'])
def login():
    form  =  LoginForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name = data['name']).first()
        if not user.check_pwd(data.get('pwd')):
            flash('账号或密码错误','err')
            return redirect(url_for('home.login'))
        session['user'] = user.name
        session['user_id'] = user.id
        userlog = UserLog(
            user_id = user.id,
            ip = request.remote_addr,
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for('home.user'))
    return render_template('/home/login.html',form = form)


# 退出
@home.route('/logout/')
def logout():
    session.pop('user',None)
    session.pop('user_id',None)
    return redirect(url_for('home.login'))


# 注册
@home.route('/register/', methods = ['GET', 'POST'])
def register():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name = data.get('name'),
            pwd = generate_password_hash(data.get('pwd')),
            email = data.get('email'),
            phone = data.get('phone'),
            uuid = uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash('注册成功','ok')
        return redirect(url_for('home.login'))
    return render_template('/home/register.html', form = form)


# 会员中心
@home.route('/users/',methods = ['GET', 'POST'])
@home_login_req
def user():
    form = UserDetailForm()
    user = User.query.get_or_404(int(session['user_id'] ))
    #第一次上传头像 初始化
    form.face.validators = []
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        # 前端记得加上enctype="multipart/form-data"
        file_face = secure_filename(form.face.data.filename)
        if not os.path.exists(app.config['UP_DIR_USER']):
            os.makedirs(app.config['UP_DIR_USER'])
            os.chmod('UP_DIR_USER', 'rw')  # 给目录授予读写权限
        user.face = change_filename(file_face)
        form.face.data.save(app.config['UP_DIR_USER'] + user.face)
        name_count = User.query.filter_by(name = data['name']).count()
        if data['name'] !=user.name and name_count == 1:
            flash('昵称已经存在','err')
            return redirect(url_for('home.user'))
        user.name = data.get('name')
        email_count = User.query.filter_by(email = data['email']).count()
        if data['email'] != user.email and email_count == 1:
            flash('邮箱已经存在', 'err')
            return redirect(url_for('home.user'))
        user.email = data.get('email')
        user.phone = data.get('phone')
        user.info = data.get('info')
        db.session.add(user)
        db.session.commit()
        flash("会员资料修改成功",'ok')
        return redirect(url_for('home.user'))
    return render_template('/home/user.html',form = form ,user =user)


# 修改密码
@home.route('/pwd/', methods = ['GET', 'POST'])
@home_login_req
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name = session['user']).first()
        # if not user.check_pwd(data.get('old_pwd')):
        #     flash('密码输入错误,请重新输入！','err')
        #     return redirect(url_for('home.pwd'))
        from werkzeug.security import generate_password_hash
        user.pwd = generate_password_hash(data.get('new_pwd'))
        db.session.add(user)
        db.session.commit()
        flash('密码修改成功,请重新登录','ok')
        return redirect(url_for('home.logout'))
    return render_template('/home/pwd.html',form = form)


# 评论页面
@home.route('/comments/<int:page>/')
@home_login_req
def comments(page=None):
    if page == None:
        page =1
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == Comment.movie_id,
        User.id == session['user_id']
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page,per_page = 10)
    return render_template('/home/comments.html',page_data=page_data)


# 电影收藏
@home.route('/moviecol/')
@home_login_req
def moviecol():
    return render_template('/home/moviecol.html')


# 会员登录日志
@home.route('/loginlog/<int:page>',methods = ['GET'])
@home_login_req
def loginlog(page = None):
    if page == None:
        page = 1
    page_data = UserLog.query.join(
        User
    ).filter(
        UserLog.user_id == User.id
    ).order_by(
        UserLog.addtime.desc()
    ).paginate(page,per_page = 10)
    return render_template('/home/loginlog.html',page_data = page_data)


# 动画 preview
@home.route('/animation/')
@home_login_req
def animation():
    data  = Preview.query.all()
    return render_template('/home/animation.html',data = data)


# 搜索
@home.route('/search/<int:page>')
@home_login_req
def search(page=None):
    if page == None:
        page = 1
    key = request.args.get('key','')
    movie_count = Movie.query.filter(
        Movie.title.ilike('key')
    ).count()
    page_data = Movie.query.filter(
        #模糊匹配
        Movie.title.ilike('%'+key+'%')
    ).order_by(
        Movie.addtime.desc()
    ).paginate(page=page,per_page = 10)
    return render_template('/home/search.html',key=key,page_data=page_data,movie_count=movie_count)


# 播放
@home.route('/play/<int:id>/<int:page>',methods=['GET','POST'])
@home_login_req
def play(id=None,page = None):
    movie = Movie.query.join(
        Tag
    ).filter(
        Movie.tag_id == Tag.id,
        Movie.id==int(id)
    ).first_or_404()
    if page == None:
        page =1
    page_data = Comment.query.join(
        Movie
    ).join(
        User
    ).filter(
        Movie.id == movie.id,
        User.id == session['user_id']
    ).order_by(
        Comment.addtime.desc()
    ).paginate(page=page,per_page = 10)
    movie.playnum = movie.playnum + 1
    form = CommentForm()
    if form.validate_on_submit() and 'user'in session:
        data = form.data
        comment = Comment(
            content = data.get('content'),
            movie_id = movie.id,
            user_id = Comment.user_id
        )
        db.session.add(comment)
        db.session.commit()
        movie.commentnum = movie.commentnum + 1
        flash('评论添加成功', 'ok')
        db.session.add(movie)
        db.session.commit()
        return redirect(url_for('home.play',id = movie.id,page = 1))
    db.session.add(movie)
    db.session.commit()
    return render_template('/home/play.html',movie = movie,form = form,page_data=page_data)

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='static/base/images/logo.png')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='static/base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='static/base/css/bootstrap_movie.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='static/base/css/animate.css')}}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
            padding-right: 3px;
            padding-left: 3px;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index',page=1)}}" class="navbar-brand" style="width:250px;">
                <img src="{{url_for('static',filename='static/base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default"id="do_search" ><span
                                class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index',page=1)}}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.register')}}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.user')}}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}
    {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p style="text-align: center">
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{url_for('static',filename='static/base/js/jquery.min.js')}}"></script>
<script src="{{url_for('static',filename='static/base/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static',filename='static/base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{url_for('static',filename='static/base/js/wow.min.js')}}"></script>
<script src="{{url_for('static',filename='static/lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val();
            // 跳转
            location.href="{{url_for('home.search',page=1)}}?key=" +key;
        })
    });

</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{url_for('static',filename='static/base/images/logo.png')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='static/base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='static/base/css/bootstrap_movie.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='static/base/css/animate.css')}}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
       .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9{
        padding-right: 3px;
        padding-left: 3px;
    }
        .media{
            padding:3px;
            border:1px solid #ccc
        }
    </style>
    {% block css %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index',page=1)}}" class="navbar-brand" style="width:250px;">
                <img src="{{url_for('static',filename='static/base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index',page=1)}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.user')}}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{% block content%}
{% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p style="text-align: center">
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{url_for('static',filename='static/base/js/jquery.min.js')}}"></script>
<script src="{{url_for('static',filename='static/base/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static',filename='static/base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{url_for('static',filename='static/base/js/wow.min.js')}}"></script>
<script src="{{url_for('static',filename='static/lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val();
            // 跳转
            location.href="{{url_for('home.search',page=1)}}?key=" +key;
        });
    });

</script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/menu.html
<div class="col-md-3">
    <div class="list-group">
        <a id="m-1" href="{{url_for('home.user')}}" class="list-group-item">
            <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
        </a>
        <a id="m-2" href="{{url_for('home.pwd')}}" class="list-group-item">
            <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
        </a>
        <a id="m-3" href="{{url_for('home.comments',page=1)}}" class="list-group-item">
            <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
        </a>
        <a id="m-4" href="{{url_for('home.loginlog',page=1)}}" class="list-group-item">
            <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
        </a>
        <a id="m-5" href="{{url_for('home.moviecol')}}" class="list-group-item">
            <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
        </a>
    </div>
</div>